name: tap-test
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew update-reset
      - run: brew tap ${{ github.repository }}
      - run: brew install fdml
      - run: fdml init /tmp/ci.fdml.xml --title CI --meter 3/4 --tempo 96 --figure-id f-1 --figure-name Foo
      - run: fdml validate /tmp/ci.fdml.xml
      - run: brew test fdml --verbose
